# SOURCS = main.cpp

# OBJDIR        = ../obj
# INCLUDEDIR    = ../
# OBJECTS       = $(SOURCS:.cpp=.o)
# CC          = gcc
# CXX         = g++
# CPPFLAGS = -std=c++14 -c -Wall -Werror -O3

# .PHONY: clean all
# all: $(OBJECTS) $(SOURCS)
# 	mkdir -p $(OBJDIR)
# 	mv *.o $(OBJDIR)

# .cpp.o:
# 	$(CXX) -I$(INCLUDEDIR) $(CPPFLAGS) $< -o $@

# clean:
# 	rm -rf $(OBJDIR)